### ISSUE TITLE
Archer C80 Support Data

### ISSUE THREAD

**Issue by sjthuss** [AlexandrErohin/TP-Link-Archer-C6U#17]
Hi,
I've done my best to follow the support instructions. I'd much appreciate if you are able to provide support for this model.

Thank you!
tar file with logs is attached.
[192.168.0.2.har.tar.gz](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/files/14538546/192.168.0.2.har.tar.gz)

Description of what I did:
0) log in
 1) Open main page
2) click on client list
3) wireless settings
4) enable 2.4 GHz, save. Disable 2.4 GHz, save
5) disable 5 Ghz, save. enable 5 GHz, save
6) Internet status page (mac, internet ip, subnet mask)
7) Archer C80 status page (with quick toggles for wireless networks etc)
8) toggle 2.4 Ghz network
9) toggle 5 Ghz network
10) toggle 2.4 GHz network (on)
11) toggle 2.4 GHz guest network
12) toggle 5 GHz guest network
13) toggle 2.4 GHz IoT network
14) toggle 5 GHz IoT network
15) system reboot
16) log in again
17) log out

**Comment by sjthuss** [comment]
> Hi! What is your router hardware version?

Firmware Version:
1.13.1 Build 230609 Rel.32076n(4341)
Hardware Version:
Archer C80 1.0

Thank you

**Comment by AlexandrErohin** [comment]
Duplicate of https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/11
