### ISSUE TITLE
Reading received SMS

### ISSUE THREAD

**Issue by iursevla** [AlexandrErohin/TP-Link-Archer-C6U#19]
I'm deciding on what Router to buy and I need the capacity to retrieve existing SMS. I saw in the code that it can send but didn't find the API to retrieve received messages.

Is there something blocking the implementation or it was just not yet implemented?

If it's the latter I can take a look when I buy one (thinking on Archer MR600 V3).

**Comment by AlexandrErohin** [comment]
Hi,
I only needed send sms, so I didn't implement receiving

**Comment by iursevla** [comment]
Hi,

 When I get the router I'll try to implement the SMS receiving part. 

 Thanks, @AlexandrErohin for your awesome work

**Comment by AlexandrErohin** [comment]
Hi
This feature was added and also set_sms_read, delete_sms and send_ussd to TPLinkMRClient

**Comment by AlexandrErohin** [comment]
I have released version [v5.1.0](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/releases/tag/v5.1.0)
