### ISSUE TITLE
Archer C80 (C6V4) Support Data

### ISSUE THREAD

**Issue by sweeeeper** [AlexandrErohin/TP-Link-Archer-C6U#28]
Login
Display wifi clients
Wifi
Guest network enable
Guest network disable
System
Logoff
[Tp-Link C6V4.zip](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/files/15449136/Tp-Link.C6V4.zip)

Firmware version 1.13.2 Build 230824 Rel.75032n(5255)
Аппаратная версия: Archer C80 2.20
Home assistant error by adding: "Your router is not supported. Please add your router support to https://github.com/AlexandrErohin/TP-Link-Archer-C6U by implementing methods for TplinkC6V4Router class"

**Comment by Smiie-2** [comment]
Getting the same issue.

Firmware Version:
1.13.2 Build 230824 Rel.74702n(4555)
Hardware Version:
Archer C80 1.0

**Comment by AlexandrErohin** [comment]
https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/15
