### ISSUE TITLE
Devices listed missing values

### ISSUE THREAD

**Issue by ryirv** [AlexandrErohin/TP-Link-Archer-C6U#35]
Hi,

I've been trying to get the download speed / upload speed for the devices connected to my router (Archer AX20) and when I iterated over the devices list, the results were always None on all values not provided in the parameters of Device (upload,download, pkt sent, pkt recieved) 

The following code is reached in your client.py : 
![image](https://github.com/user-attachments/assets/9a6b7e27-9137-42f3-82e2-190c02682141)
![image](https://github.com/user-attachments/assets/5d55d234-f653-417f-b890-b8ca542f18ac)

I fixed my issue with the upload/ download by moving the value assignments here:
![image](https://github.com/user-attachments/assets/ad077107-67a7-457e-84ab-1d3aa4d15546)

Cheers 👍

**Comment by AlexandrErohin** [comment]
@ryirv Hi
Could you make a MR please for these changes?

**Comment by AlexandrErohin** [comment]
@ryirv Could you open Pull Request for these changes please?

**Comment by AlexandrErohin** [comment]
@ryirv What is your hardware version of your tplink AX1800 ?

**Comment by ryirv** [comment]
@AlexandrErohin 

Archer AX20 v3.0

**Comment by AlexandrErohin** [comment]
@ryirv Thank you
I have mage changes which is compatible with other routers. Could you check the new client version?

**Comment by AlexandrErohin** [comment]
@ryirv Added. Please try the latest version
P.S. Dont forget please to give a star to the repo :)
