### ISSUE TITLE
Archer AX1500 v2.0, firmware 1.3.10 Build 20240130 Rel. 77367(5553)

### ISSUE THREAD

**Issue by timdesrochers** [AlexandrErohin/TP-Link-Archer-C6U#41]
Just got this running. Authorization is successful with just `router = TplinkRouterProvider.get_client('http://192.168.0.1', 'plaintext-password') `, so it looks like no web encrypted password is needed. 

Able to get leases, but not firmware or status. Going to keep poking around; let me know if it would be useful to poke around anywhere in particular.

**Comment by AlexandrErohin** [comment]
Hi!
Is there any errors when you get status info?

**Comment by AlexandrErohin** [comment]
@timdesrochers Any news?
