### ISSUE TITLE
Archer C5400X v1.0 / Firmware: 1.1.7 Build 20240510 rel.17306(5553) WORKING

### ISSUE THREAD

**Issue by joluas** [AlexandrErohin/TP-Link-Archer-C6U#44]
Integration is working with this router -> https://www.tp-link.com/en/home-networking/wifi-router/archer-c5400x/

![image](https://github.com/user-attachments/assets/b948ede1-8cb8-4762-be4b-a31c9bb347b9)

Available sensors:
- sensor.tp_link_router_cpu_used
- sensor.tp_link_router_memory_used
- sensor.tp_link_router_total_clients
- sensor.tp_link_router_total_guest_wifi_clients
- sensor.tp_link_router_total_wired_clients
- Probably guest users as well but I dont have this enabled in my router

Available switches:
- switch.guest_wifi_2_4g
- switch.guest_wifi_5g
- button.reboot
- switch.wifi_2_4g
- switch.wifi_5g

Non-available sensors:
- sensor.tp_link_router_total_iot_clients

Non-available switches:
- switch.guest_wifi_6g
- switch.iot_wifi_2_4g
- switch.iot_wifi_5g
- switch.iot_wifi_6g
- switch.wifi_6g

Login with [Web Encrypted Password](https://github.com/AlexandrErohin/home-assistant-tplink-router#encrypted_pass)

If you need any test from my side, please reach out. Thanks for this incredible piece of software.

![image](https://github.com/user-attachments/assets/be167784-a243-41b1-ab30-2c86e2076896)

**Comment by joluas** [comment]
I am dumb, I was looking at an old compatibility page and I submitted this to a different github.

Sorry but incredible work.

**Comment by AlexandrErohin** [comment]
@joluas Thank you for the info!
P.S. Would be great if you could give a star to the repo :) Thanks
