### ISSUE TITLE
authorize() timeout help EX511

### ISSUE THREAD

**Issue by krlosrenan** [AlexandrErohin/TP-Link-Archer-C6U#46]
Hello, I'm trying to make the requests compatible with the EX511 router, however the request for cgi/login is executing for a very long time, until it reaches the defined timeout.

The request for /cgi/getParm is happening normally, with the data being returned by the request, as expected.

My question is, did you encounter anything similar when you were developing? And how did you solve it?

**Comment by AlexandrErohin** [comment]
[v5.1.0](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/releases/tag/v5.1.0)
