### ISSUE TITLE
AX75 V1 Exception: You need to use web encrypted password instead. Check the documentation! BUT its in Clear Text?!

### ISSUE THREAD

**Issue by kali-777** [AlexandrErohin/TP-Link-Archer-C6U#48]
First of all many thanks for this, looks very **promising** 🤩

However its NOT working for me with AX75 v1...

from tplinkrouterc6u import (
    TplinkRouterProvider,
    TplinkRouter,
    TplinkC1200Router,
    TPLinkMRClient,
    TPLinkDecoClient,
    Connection
)
from logging import Logger

Set up the router connection
host = 'https://192.168.2.240'  # Replace with your router's IP address
username = 'admin'  # Replace with your router's username
password = '*****'  # Replace with your router's password

Get the router client
router = TplinkRouterProvider.get_client(host, password, username)

if router:
    # Authorize and get the status
    router.authorize()
    status = router.get_status()
    print("Router Status:", status)
    router.logout()
else:
    print("Unable to connect to the router.")

When try to run it, i got Exception....

`
(tplinkenv) kali@raspi5:/Projects/Python/TP-Link-Archer-C6U/test $ python get_status.py
Traceback (most recent call last):
  File "/Projects/Python/TP-Link-Archer-C6U/test/get_status.py", line 13, in <module>
    router.authorize()
  File "/usr/local/share/miniforge/envs/tplinkenv/lib/python3.11/site-packages/tplinkrouterc6u-4.2.2-py3.11.egg/tplinkrouterc6u/client.py", line 697, in authorize
Exception: You need to use web encrypted password instead. Check the documentation!
`

BUT when i done on Chrome Console its give back my password in clear text?! 🤔

`
document.querySelector('input[type="password"]').value;
`

Please suggest!

**Comment by AlexandrErohin** [comment]
It was tested on AX75 V1.
Do you have the latest hardware version for AX75 V1 ?

Could you try this?
```
from logging import Logger
from tplinkrouterc6u import TplinkRouter


router = TplinkRouter('http://192.168.0.1', 'you_plain_password', logger=Logger('test'))

router.authorize()

firmware = router.get_firmware()
print(firmware.firmware_version)

status = router.get_status()
print(status.wired_total)
```

**Comment by kali-777** [comment]
Sorry my bad its AX73, thanks a LOT its working now! 🤗
I want get Public IP also export ALL FIX-DHCP Reservation Entries, coz i have Smart Home with Home Assistant & other Devices, SO i over limit of 64x FIX-DHCP address i need to move Pi-hole/DNSMasq 😣

`1.3.6 Build 20240325 rel.39241(5553)
28`
