### ISSUE TITLE
LTE_USSD support

### ISSUE THREAD

**Issue by ifarbod** [AlexandrErohin/TP-Link-Archer-C6U#52]
It'd be cool for this library to support sending USSD requests and obtaining the responses, How should the API for it be designed?

![brave_efu3CllPst](https://github.com/user-attachments/assets/fdd1539a-fa63-4ce3-a8e5-2a8e413bee15)

**Comment by AlexandrErohin** [comment]
Hi,
I have added get_sms, set_sms_read, delete_sms and send_ussd to TPLinkMRClient. Please test it. I didnt release new version yet. Please download from repository the client and test

**Comment by ifarbod** [comment]
send_ussd works as intended, I can't test the MSS functions due to the sim card's limitations unfortunately

**Comment by AlexandrErohin** [comment]
I have released version [v5.1.0](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/releases/tag/v5.1.0)
